#!/usr/bin/env python

import unittest

from test import testCore, testOperation, testParser

suite1 = testCore.suite()
suite2 = testOperation.suite()
suite3 = testParser.suite()

suite = unittest.TestSuite()
suite.addTest(suite1)
suite.addTest(suite2)
suite.addTest(suite3)

unittest.TextTestRunner(verbosity=0).run(suite)


